### ISSUE TITLE
Stuck on Refresh flow

### ISSUE THREAD

**Issue by odanu** [tink-ab/tink-link-ios#40]
https://user-images.githubusercontent.com/1110408/119839692-07b95a80-bf0d-11eb-9f26-b11bb4b7646e.mp4

Hey hey. We are getting stuck with the Refresh Token flow, as you can see in the video attach. Also please note that the `Cancel` button is not responsive.

Some details:
Credentials ID: 6bb9a09a4dcb4cd2aa8b2b4126d5a0df
Code:
```
        let configuration = Tink.Configuration(
            clientID: Constants.TinkLink.clientId,
            appURI: URL(string: Constants.Branch.tinkLinkRedirectUri)
        )
        Tink.configure(with: configuration)

        let credentials = Credentials.ID(credentialsId)
            let operation = TinkLinkViewController.Operation.refresh(credentialsID: credentials, forceAuthenticate: true)
            let tinkLinkViewController = TinkLinkViewController(operation: operation) { result in
                do {
                    let credentials = try result.get()
                    delegate.tinkLinkSuccessHandler(credentials)
                } catch {
                    // Handle any errors
                    if let error = error as? TinkLinkError {
                        delegate.tinkLinkErrorHandler(error)
                    }
                }
            }
```
<img width="149" alt="Screenshot 2021-05-27 at 17 10 01" src="https://user-images.githubusercontent.com/1110408/119841395-6d5a1680-bf0e-11eb-9309-b7c1baf8f0fe.png">

**Comment by lilSwifty** [comment]
Hey! 👋  Thank you reporting, we will investigate this internally and return with answer.

**Comment by menghaozhang** [comment]
Hey, this seems because your access token is not valid, or perhaps you did not set the user session before you use the `TinkLinkViewController `? 
You can do like this:
```
Tink.shared.userSession = .accessToken("Your AccessToken")
```
We can try to improve our error handling to make this more obvious.

**Comment by odanu** [comment]
@menghaozhang Hmm... should we use the same access token as the one we linked the bank account with? Or we should create a fresh access token for  this operation?

**Comment by menghaozhang** [comment]
I would say that is up to you, all you need to take care is you need a valid access token. So if your original access token has expired then you need to refresh it or use a new access token.
If you choose to use the authorization code, then you can try to authenticate a permanent user with `authenticateUser(authorizationCode:completion:)` in you tink instance.

**Comment by menghaozhang** [comment]
Hey, are you able to resolve this issue by adding access token with the new released version? If so I am going to close this issue.

**Comment by odanu** [comment]
Hey @menghaozhang thanks for asking. We need to do some modifications on the backend first and the backend dev just arrived today from his vacation. So hopefully, we are going to kill this issue this week. 
I promise you I will get back with feedback and close the ticket if it solves.

**Comment by menghaozhang** [comment]
Great to hear, just want to point out that please note that we are happy to see open source feedbacks. But we dont encourage using github open source issues as an official portal to report or asking for feature requirement. Please go through our official [support channel](https://tinkab.atlassian.net/servicedesk/customer/portals).

**Comment by odanu** [comment]
@menghaozhang Looks like the suggestions you did above worked well.
Few things  to mention though:
1. It would be great to improve the documentation on this part
2. When testing in sandbox, the redirect  back from third party doesn't work. I already opened a ticket  in the support channel.

**Comment by menghaozhang** [comment]
The issue described above has been fixed.
