### ISSUE TITLE
Change Permanent User Market

### ISSUE THREAD

**Issue by odanu** [tink-ab/tink-link-ios#43]
Hi,

With reference to this ticket https://tinkab.atlassian.net/servicedesk/customer/portal/5/AS-3465.
Would it be possible to enable changing permanent user market from the iOS SDK side?

Thanks

**Comment by lilSwifty** [comment]
Hi @odanu this is not possible at the moment and since it is a feature request it will be handled in the ticket you mentioned. Therefore I will close this Issue for now.

**Comment by menghaozhang** [comment]
We are working on this one to allow adding credentials from different market, it will be available in our next release.

**Comment by menghaozhang** [comment]
Hey @odanu, please see the latest release for more information about adding credentials from different markets for permanent user. 
https://github.com/tink-ab/tink-link-ios/releases/tag/1.3.0

Closing this issue now since the corresponding feature has been released.

**Comment by odanu** [comment]
Thanks @menghaozhang

**Comment by menghaozhang** [comment]
I dont have the access to the ticket you created, maybe only the support team can see it. I will try to help you bring this up to the corresponding team.
