### ISSUE TITLE
Hide initial loading screen and unable to dismiss it

### ISSUE THREAD

**Issue by JordiGamez** [tink-ab/tink-link-ios#47]
Since the 1.2.0 TinkLink iOS SDK version, when I start the TinkLink SDK using the updated initialiser:

```
let viewController = TinkLinkViewController(tink: .shared, operation: operation) { result in
  //
}
```

It displays a new initial loading screen:

<img width="200" alt="32875d6d-297c-4072-afab-529ee96a31cd" src="https://user-images.githubusercontent.com/10868434/128499701-416b387d-4659-45f5-a516-02102dc174c7.png">

Is there a way to remove this new loading screen and directly display the entity login screen as the previous 0.18.0 iOS SDK version?

<img width="200" alt="61fd1684-2678-41fd-9a7e-12b079cd780d" src="https://user-images.githubusercontent.com/10868434/128500139-885095c2-9de5-4876-977f-1fa072cbdf1e.png">

**Comment by menghaozhang** [comment]
Hey, thanks for reporting! This is an unknown issue that I also noticed. Will take a look in the future.

**Comment by menghaozhang** [comment]
Hey, I have fixed the issue to allow the user able to go back to loading screen when update credentials, so you can check the latest release, see if that works for you. Closing this issue now.
